version: '3.8'
services:
  glue:
    # image: amazon/aws-glue-libs:glue_libs_1.0.0_image_01
    build:
      context: ./docker/glue
    command: /opt/amazon/bin/gluesparksubmit src/show.py
    working_dir: /workspace
    volumes:
      - .:/workspace
    env_file:
      - aws_credentials.env
