version: '3.8'
services:
  glue:
    image: amazon/aws-glue-libs:glue_libs_1.0.0_image_01
    command: /home/aws-glue-libs/bin/gluesparksubmit src/show.py
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 8888:8888
      - 4040:4040
    env_file:
      - aws_credentials.env
